### ISSUE TITLE
Audio/Video Updates in Chrome 63/64

### ISSUE THREAD

**Issue by beaufortfrancois** [demuxed/demuxed-weekly#11]
https://developers.google.com/web/updates/2017/12/chrome-63-64-media-updates

- Web developers can now predict whether playback will be smooth and power efficient.
- Chrome now supports HDR video playback on Windows 10.
- Offline playback with persistent licenses are now supported on Windows and Mac.
- The default preload value for <video> and <audio> elements is now "metadata".
- An error is now thrown when media playbackRate is unsupported.
- Chrome now pauses all background video-only media.
- Audio is not muted anymore for extreme playbackRate.

**Comment by mmcc** [comment]
Excellent! Going to tweet this out now.

**Comment by beaufortfrancois** [comment]
Yeah! https://twitter.com/demuxed/status/943600396794134528
